baseURL: https://savvas.live
languageCode: en-us
title: sio Blog
theme: maupassant

params:
  author: "sio"
  subtitle: "Privacy enthousiast, Computer networks and Music Lover"
  keywords: "Privacy enthousiast, Computer networks and Music Lover"
  description: "Privacy enthousiast, Computer networks and Music Lover"

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3